services:
  api-rest:
    env_file: .env
    container_name: api-rest
    build:
      context: .
      args:
        - PORT=${PORT:-8443}
    working_dir: /api-rest
    ports:
      - '${PORT:-8443}:${PORT:-8443}'
      - 9229:9229
    volumes:
      - ./src:/api-rest/src
      - ./test:/api-rest/test
